### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by edoardoted99** [simon-r/PyParticles#12]
edo@edo-HP-Pavilion-Laptop-14-ce0xxx:~/coding/particles$ pyparticles_app --test harmonic

Start a test simulation:
 It compares the simulated solution with the analytical solution in a specific problem
Traceback (most recent call last):
  File "/home/edo/anaconda3/bin/pyparticles_app", line 25, in <module>
    main.main()
  File "/home/edo/anaconda3/lib/python3.8/site-packages/pyparticles/main/main.py", line 106, in main
    tst.test( options.test )
  File "/home/edo/anaconda3/lib/python3.8/site-packages/pyparticles/demo/test.py", line 33, in test
    tst.build_animation()
  File "/home/edo/anaconda3/lib/python3.8/site-packages/pyparticles/animation/test_animation.py", line 224, in build_animation
    self.pset = ps.ParticlesSet( 2 , 3 )
  File "/home/edo/anaconda3/lib/python3.8/site-packages/pyparticles/pset/particles_set.py", line 94, in __init__
    if self.__mass  != None :
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by duxngsi** [comment]
Same issue

**Comment by gxusthjw** [comment]
Same issue

**Comment by simon-r** [comment]
Fixed in the git version
